title: Project Documentation
theme: just-the-docs
baseurl: '/test_docs'
logo: './assets/logo.png'
enable_copy_code_button: true
mermaid:
  version: '11.6.0' # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
last_edit_timestamp: true
